### ISSUE TITLE
save and cancel button is missing

### ISSUE THREAD

**Issue by FriedePretty** [scout-tools/anmelde-tool#121]
save and cancel button is missing

![Pfadis1](https://user-images.githubusercontent.com/78742118/107234708-3aa21600-6a24-11eb-95f7-18e75677912a.JPG)

**Comment by RobertBagdahn** [comment]
![image](https://user-images.githubusercontent.com/54767884/107235752-50640b00-6a25-11eb-90c4-0191826e2158.png)

Hinzugefügt
