### ISSUE TITLE
Pflichtfeld sollte rot markiert sein

### ISSUE THREAD

**Issue by FriedePretty** [scout-tools/anmelde-tool#123]
![Bundeslager](https://user-images.githubusercontent.com/78742118/107250340-29610580-6a34-11eb-8f4b-2dfd28937dee.JPG)

**Comment by RobertBagdahn** [comment]
Ja, das prüfe ich, das ist ein wenig kompliziert, weil es ja hier nicht bearbeitet werden darf :-(

**Comment by RobertBagdahn** [comment]
erledigt
