### ISSUE TITLE
click "Meine persönlichen Daten löschen", nichts passiert

### ISSUE THREAD

**Issue by FriedePretty** [scout-tools/anmelde-tool#124]
![delete](https://user-images.githubusercontent.com/78742118/107252823-03d4fb80-6a36-11eb-88c3-e68c02eda012.JPG)

**Comment by FriedePretty** [comment]
Der Account wird offensichtlich gelöscht(?). Es fehlt aber die Rückmeldung.

**Comment by RobertBagdahn** [comment]
Ohhh, ja....das muss ich noch bauen ;-)

**Comment by FriedePretty** [comment]
Ist es sinnvoll einen Accout zu löschen, wenn dieser Account noch ein Lager angemeldet hat? Ich kann dieses momentan nicht testen, da die Lageranmeldung nicht funktioniert,

**Comment by RobertBagdahn** [comment]
Guter Punkt, das müssen wir nochmal durchdenken.
Wahrscheinlich sollten wir die Daten erst endgültig nach dem Lager löschen?!?

Nächste Woche werde ich nochmal den Datenschutz durchdenken und niederschreiben, da wird das auf jeden Fall nochmal Thema sein
