### ISSUE TITLE
"Lageranmeldung bearbeiten" update funktioniert nicht

### ISSUE THREAD

**Issue by FriedePretty** [scout-tools/anmelde-tool#125]
Step 1:  Click link im Mail

Step 2: Anmeldung für Lager  "stadt und spiel" und abschließen

![bearbeiten](https://user-images.githubusercontent.com/78742118/107258583-44377800-6a3c-11eb-9f94-1b9a06f12044.JPG)

Step 3: Logout

Step 4: click Link von Step1 erneut 

Step 5: Lageranmeldung ändern
![bearbeiten](https://user-images.githubusercontent.com/78742118/107258244-df7c1d80-6a3b-11eb-8339-e67ec289a489.JPG)

Folgendes wird beobachtet:

Keine Daten werden angezegt, wenn  "weiter"  geclickt wird.

**Comment by RobertBagdahn** [comment]
Aktuell kann man nur die Mosaik "Bundesfahrt" speichern. Der Rest ist noch in einem frühen Entwicklungsstatus.
Aber die Bundesfahrt ist auch die wichtigste Fahrt, die muss in 2 1/2 Wochen Live gehen.
