### ISSUE TITLE
Lageranmeldung wird nicht gespeichert

### ISSUE THREAD

**Issue by FriedePretty** [scout-tools/anmelde-tool#127]
step 1: Anmelden für "stadt und spiel"
step 2: Click Abschliessen
![abschliet](https://user-images.githubusercontent.com/78742118/107263554-2ec54c80-6a42-11eb-8d7b-1c44fdbfe9ca.JPG)

Daten werden nicht gespeichert
siehe #125

**Comment by RobertBagdahn** [comment]
Gleicher Grund wie bei #125: Ist noch in einer frühen Entwicklung
