### ISSUE TITLE
erneutes Anmelden mit Link/Tolen funktioniert nicht immer

### ISSUE THREAD

**Issue by FriedePretty** [scout-tools/anmelde-tool#129]
step 1 : click Link vom mail
step2:  click  etwas
step3: logout
step4: nach 10 Stunden click Link vom mail in step1 um sich neu anzumelden
error
![Token](https://user-images.githubusercontent.com/78742118/107335099-d2047900-6ab7-11eb-901c-64fdd34d16d2.JPG)

**Comment by RobertBagdahn** [comment]
:'-(

**Comment by RobertBagdahn** [comment]
Jede Nacht löscht sich die Datenbank komplett und deswegen war der Code nicht mehr im System.
Aber ich Fehlermeldung ist nicht so "sprechend" ich mache sie mal schöner

**Comment by FriedePretty** [comment]
Folgender Text im Mail sollte entspr, angepasst werden:
"Der Link ist nur 24h gültig.. "

Folgendes, wie im Mail beschrieben, funktioniert so auch nicht?
...Falls er schon abgelaufen ist, kannst du dir hier einen neuen zusenden lassen.
"Klicke hier um dich anzumelden"

**Comment by RobertBagdahn** [comment]
Auf dem "echten" Server wird das funktionieren, aber wir arbeiten noch auf dem Test-Server.
Damit das klar wird, habe ich jetzt extra die Logos ausgetauscht.

Aber ich mache das nochmal klarer, 
Ab nächsten Montag haben wir dann endlich auch unseren Produktiv-Server

**Comment by FriedePretty** [comment]
okay, noch eine Frage zum Account:
Mein Account ist die e-mail Adresse, richtig?
Das Password wird automatisch erzeugt, richtig?
Meine Anmeldung für ein Lager ist verknüpft mit der e-mail Adresse , richtig?
Was passiert, wenn ich im Profil meinen Stamm ändere und diesen ebenfalls anmelde? D,h. kann ich mit einem Account zwei Stämme anmelden.

**Comment by RobertBagdahn** [comment]
Ja, ein Account kann mehrere Stämme anmelden.
Eine Anmeldung kann allerdings auch mehreren Accounts zugewiesen werden. (Also ich melde meinen Stamm an und Alina darf meine Anmeldung sehen und bearbeiten)
Jeder Stamm kann aber nur einmal pro Aktion angelegt werden.

Das Zuweisen von Accounts zu Anmeldungen können wir im Moment im Backend veränderung und anpassen. (Dort gibt es nochmal Pfelge-Eingabemasken für Administratoren)

Hat das ganze System Schwachstellen?
Ja, das ganze hat Probleme, aber alle anderen Konzepte haben noch mehr Probleme ;-)
Wenn du eine gute Idee hast, können wir dort gerne noch mehr Sicherheitsfaktoren einbauen, aber mir fällt nichts praktikableres ein. :-(

**Comment by FriedePretty** [comment]
okay, kannst du mir die Datenbank Tabellen zukommen lassen. Ich denke um die Anforderungen zu erfüllen die du oben genannt hast, müsste man beim Lageranmelden als erstes den Stamm auswählen den man anmelden will. Nicht einfach den Stamm vom Profil nehmen.
